In [368]:
# HUGE shout out to https://www.kaggle.com/headsortails/pytanic for the guide. Extremely in depth feature decomposition
#%matplotlib inline

# for seaborn issue:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from scipy import stats
import sklearn as sk
import itertools
import json
from re import sub
from decimal import Decimal
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
from statsmodels.graphics.mosaicplot import mosaic
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.graph_objs import *
import pickle
import math



from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

sns.set(style='white', context='notebook', palette='deep')

In [369]:
data = pd.read_csv('./Economics/Real Estate/Airbnb Seattle Listings/listings.csv')
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 92 columns):
id                                  3818 non-null int64
listing_url                         3818 non-null object
scrape_id                           3818 non-null int64
last_scraped                        3818 non-null object
name                                3818 non-null object
summary                             3641 non-null object
space                               3249 non-null object
description                         3818 non-null object
experiences_offered                 3818 non-null object
neighborhood_overview               2786 non-null object
notes                               2212 non-null object
transit                             2884 non-null object
thumbnail_url                       3498 non-null object
medium_url                          3498 non-null object
picture_url                         3818 non-null object
xl_picture_url                      3498 non-null object
host_id                             3818 non-null int64
host_url                            3818 non-null object
host_name                           3816 non-null object
host_since                          3816 non-null object
host_location                       3810 non-null object
host_about                          2959 non-null object
host_response_time                  3295 non-null object
host_response_rate                  3295 non-null object
host_acceptance_rate                3045 non-null object
host_is_superhost                   3816 non-null object
host_thumbnail_url                  3816 non-null object
host_picture_url                    3816 non-null object
host_neighbourhood                  3518 non-null object
host_listings_count                 3816 non-null float64
host_total_listings_count           3816 non-null float64
host_verifications                  3818 non-null object
host_has_profile_pic                3816 non-null object
host_identity_verified              3816 non-null object
street                              3818 non-null object
neighbourhood                       3402 non-null object
neighbourhood_cleansed              3818 non-null object
neighbourhood_group_cleansed        3818 non-null object
city                                3818 non-null object
state                               3818 non-null object
zipcode                             3811 non-null object
market                              3818 non-null object
smart_location                      3818 non-null object
country_code                        3818 non-null object
country                             3818 non-null object
latitude                            3818 non-null float64
longitude                           3818 non-null float64
is_location_exact                   3818 non-null object
property_type                       3817 non-null object
room_type                           3818 non-null object
accommodates                        3818 non-null int64
bathrooms                           3802 non-null float64
bedrooms                            3812 non-null float64
beds                                3817 non-null float64
bed_type                            3818 non-null object
amenities                           3818 non-null object
square_feet                         97 non-null float64
price                               3818 non-null object
weekly_price                        2009 non-null object
monthly_price                       1517 non-null object
security_deposit                    1866 non-null object
cleaning_fee                        2788 non-null object
guests_included                     3818 non-null int64
extra_people                        3818 non-null object
minimum_nights                      3818 non-null int64
maximum_nights                      3818 non-null int64
calendar_updated                    3818 non-null object
has_availability                    3818 non-null object
availability_30                     3818 non-null int64
availability_60                     3818 non-null int64
availability_90                     3818 non-null int64
availability_365                    3818 non-null int64
calendar_last_scraped               3818 non-null object
number_of_reviews                   3818 non-null int64
first_review                        3191 non-null object
last_review                         3191 non-null object
review_scores_rating                3171 non-null float64
review_scores_accuracy              3160 non-null float64
review_scores_cleanliness           3165 non-null float64
review_scores_checkin               3160 non-null float64
review_scores_communication         3167 non-null float64
review_scores_location              3163 non-null float64
review_scores_value                 3162 non-null float64
requires_license                    3818 non-null object
license                             0 non-null float64
jurisdiction_names                  3818 non-null object
instant_bookable                    3818 non-null object
cancellation_policy                 3818 non-null object
require_guest_profile_picture       3818 non-null object
require_guest_phone_verification    3818 non-null object
calculated_host_listings_count      3818 non-null int64
reviews_per_month                   3191 non-null float64
dtypes: float64(17), int64(13), object(62)
memory usage: 2.7+ MB
None

In [370]:
features = ['listing_url', 'neighbourhood', 'weekly_price', 'monthly_price', 'property_type','longitude','latitude', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'price', 'require_guest_profile_picture', 'calculated_host_listings_count', 'review_scores_rating']

area_map = {
    "Wedgwood": "Wedgewood",
    "North Queen Anne": "Queen Anne",
    "East Queen Anne": "Queen Anne",
    "West Queen Anne": "Queen Anne",
    "South Queen Anne": "Queen Anne",
    "Broadway": "Capitol Hill",
    "Adams": "Ballard",
    "Briarcliff": "Magnolia",
    "Loyal Heights": "Ballard",
    "Mann": "Minor",
    "Mid-Beacon Hill": "North Beacon Hill",
    "Pike-Market": "Pike Place Market",
    "Southeast Magnolia": "Magnolia",
    "Sunset Hill": "Ballard",
    "West Woodland": "Ballard",
    "Whittier Heights": "Ballard"
}

def apply(x):
    try:
        return area_map[x]
    except KeyError:
        return x

data["neighbourhood"] = data["neighbourhood"].fillna(data["neighbourhood"])
data['neighbourhood'] = data['neighbourhood'].apply(apply)

df = data[features]
df = df.loc[df['review_scores_rating'].notnull()]

# listing_url                       3171 non-null object
# neighbourhood            3171 non-null object
# weekly_price                      1792 non-null object
# monthly_price                     1356 non-null object
# property_type                     3171 non-null object
# longitude                         3171 non-null float64
# latitude                          3171 non-null float64
# room_type                         3171 non-null object
# accommodates                      3171 non-null int64
# bathrooms                         3171 non-null int32
# bedrooms                          3171 non-null int32
# beds                              3171 non-null int32
# bed_type                          3171 non-null object
# amenities                         3171 non-null object
# price                             3171 non-null float64
# require_guest_profile_picture     3171 non-null int64
# calculated_host_listings_count    3171 non-null int64
# review_scores_rating              3171 non-null float64

# we want to predict review_scores_rating
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3171 entries, 0 to 3814
Data columns (total 18 columns):
listing_url                       3171 non-null object
neighbourhood                     2866 non-null object
weekly_price                      1792 non-null object
monthly_price                     1356 non-null object
property_type                     3171 non-null object
longitude                         3171 non-null float64
latitude                          3171 non-null float64
room_type                         3171 non-null object
accommodates                      3171 non-null int64
bathrooms                         3159 non-null float64
bedrooms                          3165 non-null float64
beds                              3171 non-null float64
bed_type                          3171 non-null object
amenities                         3171 non-null object
price                             3171 non-null object
require_guest_profile_picture     3171 non-null object
calculated_host_listings_count    3171 non-null int64
review_scores_rating              3171 non-null float64
dtypes: float64(6), int64(2), object(10)
memory usage: 470.7+ KB

In [371]:
field_index_mapping = {
    "neighbourhood": "neighbourhood_indexed",
    "property_type": "property_indexed",
    "room_type": "room_indexed",
    "bed_type": "bed_indexed",
    "require_guest_profile_picture": "require_guest_profile_picture"
}
for field in ["neighbourhood", "property_type", "room_type", "bed_type", "require_guest_profile_picture"]:
    val_types = df[field].unique()
    val_map = dict.fromkeys(val_types)
    for i, el in enumerate(val_types):
        val_map[el] = i
    df[field_index_mapping[field]] = df[field].map(val_map)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3171 entries, 0 to 3814
Data columns (total 22 columns):
listing_url                       3171 non-null object
neighbourhood                     2866 non-null object
weekly_price                      1792 non-null object
monthly_price                     1356 non-null object
property_type                     3171 non-null object
longitude                         3171 non-null float64
latitude                          3171 non-null float64
room_type                         3171 non-null object
accommodates                      3171 non-null int64
bathrooms                         3159 non-null float64
bedrooms                          3165 non-null float64
beds                              3171 non-null float64
bed_type                          3171 non-null object
amenities                         3171 non-null object
price                             3171 non-null object
require_guest_profile_picture     3171 non-null int64
calculated_host_listings_count    3171 non-null int64
review_scores_rating              3171 non-null float64
neighbourhood_indexed             3171 non-null int64
property_indexed                  3171 non-null int64
room_indexed                      3171 non-null int64
bed_indexed                       3171 non-null int64
dtypes: float64(6), int64(7), object(9)
memory usage: 569.8+ KB

In [372]:
for types in ["bathrooms", "bedrooms", "beds"]:
    df[types] = df[types].apply(lambda x: 1 if np.isnan(x) else x)
    df[types] = df[types].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3171 entries, 0 to 3814
Data columns (total 22 columns):
listing_url                       3171 non-null object
neighbourhood                     2866 non-null object
weekly_price                      1792 non-null object
monthly_price                     1356 non-null object
property_type                     3171 non-null object
longitude                         3171 non-null float64
latitude                          3171 non-null float64
room_type                         3171 non-null object
accommodates                      3171 non-null int64
bathrooms                         3171 non-null int32
bedrooms                          3171 non-null int32
beds                              3171 non-null int32
bed_type                          3171 non-null object
amenities                         3171 non-null object
price                             3171 non-null object
require_guest_profile_picture     3171 non-null int64
calculated_host_listings_count    3171 non-null int64
review_scores_rating              3171 non-null float64
neighbourhood_indexed             3171 non-null int64
property_indexed                  3171 non-null int64
room_indexed                      3171 non-null int64
bed_indexed                       3171 non-null int64
dtypes: float64(3), int32(3), int64(7), object(9)
memory usage: 532.6+ KB

In [373]:
# processing prices
df["price"] = df["price"].apply(lambda x: float(Decimal(sub(r'[^\d.]', '', x))))
df["has_monthly_price"] = df["monthly_price"].isnull() == False
df["has_weekly_price"] = df["weekly_price"].isnull() == False

In [374]:
# for i, am in enumerate(df["amenities"]):

def parse_amenity(s):
    s = s[2:-2]
    s = s.replace('"', '')
    res = s.split(",")
    return res
parse_amenity(df["amenities"][13])
df["amenities"] = df["amenities"].apply(parse_amenity)
df["amenities"][1]

['V',
 'Internet',
 'Wireless Internet',
 'Kitchen',
 'Free Parking on Premises',
 'Buzzer/Wireless Intercom',
 'Heating',
 'Family/Kid Friendly',
 'Washer',
 'Dryer',
 'Smoke Detector',
 'Carbon Monoxide Detector',
 'First Aid Kit',
 'Safety Card',
 'Fire Extinguisher',
 'Essential']

In [375]:
df["event_suitable"] = df["amenities"].apply(lambda x: True if 'Suitable for Events' in x else False)
df["event_suitable"].unique()
df["event_suitable"].value_counts()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3171 entries, 0 to 3814
Data columns (total 25 columns):
listing_url                       3171 non-null object
neighbourhood                     2866 non-null object
weekly_price                      1792 non-null object
monthly_price                     1356 non-null object
property_type                     3171 non-null object
longitude                         3171 non-null float64
latitude                          3171 non-null float64
room_type                         3171 non-null object
accommodates                      3171 non-null int64
bathrooms                         3171 non-null int32
bedrooms                          3171 non-null int32
beds                              3171 non-null int32
bed_type                          3171 non-null object
amenities                         3171 non-null object
price                             3171 non-null float64
require_guest_profile_picture     3171 non-null int64
calculated_host_listings_count    3171 non-null int64
review_scores_rating              3171 non-null float64
neighbourhood_indexed             3171 non-null int64
property_indexed                  3171 non-null int64
room_indexed                      3171 non-null int64
bed_indexed                       3171 non-null int64
has_monthly_price                 3171 non-null bool
has_weekly_price                  3171 non-null bool
event_suitable                    3171 non-null bool
dtypes: bool(3), float64(4), int32(3), int64(7), object(8)
memory usage: 701.9+ KB

In [376]:
drop_features = ['neighbourhood', 'listing_url', 'weekly_price', 'monthly_price', 'property_type', 'room_type', 'bed_type', 'amenities', 'require_guest_profile_picture', 'calculated_host_listings_count']
train_input = df.drop(drop_features, axis=1)
print(train_input.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3171 entries, 0 to 3814
Data columns (total 15 columns):
longitude                3171 non-null float64
latitude                 3171 non-null float64
accommodates             3171 non-null int64
bathrooms                3171 non-null int32
bedrooms                 3171 non-null int32
beds                     3171 non-null int32
price                    3171 non-null float64
review_scores_rating     3171 non-null float64
neighbourhood_indexed    3171 non-null int64
property_indexed         3171 non-null int64
room_indexed             3171 non-null int64
bed_indexed              3171 non-null int64
has_monthly_price        3171 non-null bool
has_weekly_price         3171 non-null bool
event_suitable           3171 non-null bool
dtypes: bool(3), float64(4), int32(3), int64(5)
memory usage: 454.2 KB
None

In [377]:
scaler = MinMaxScaler()
svd = TruncatedSVD(n_components=3)

scaler.fit(train_input)

train_scaled = scaler.transform(train_input)

encoder = OneHotEncoder()

encoder.fit(train_scaled)

with open('svd.pickle', 'wb') as handle:
    pickle.dump(svd, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('encoder.pickle', 'wb') as handle:
    pickle.dump(encoder, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('scaler.pickle', 'wb') as handle:
    pickle.dump(scaler, handle, protocol=pickle.HIGHEST_PROTOCOL)
train_encoded = encoder.transform(train_scaled)

train_svd = svd.fit_transform(train_encoded)

In [378]:
# est = KMeans(n_clusters=5)
# est.fit(df_std)
# labels = est.labels_
agg = AgglomerativeClustering(n_clusters=5)
labels = agg.fit_predict(train_svd)
clf = LinearSVC()
clf.fit(train_input, labels)

with open('agg.pickle', 'wb') as handle:
    pickle.dump(clf, handle, protocol=pickle.HIGHEST_PROTOCOL)
# now clf.predict(input) will give you the correct label
labels.shape

(3171,)

In [379]:
fun = np.vectorize((lambda x: x * 2))
trace1 = go.Scatter3d(
#     x=df[features[0]],
#     y=df[features[1]],
#     z=df[features[2]],
    x=train_svd[:, 0],
    y=train_svd[:, 1],
    z=train_svd[:, 2],
    mode='markers',
    marker=dict(
        size=2,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        color=fun(labels).astype(np.float),
        opacity=0.8
    )
)
layout = go.Layout(
    scene=Scene(
    xaxis=dict(
        title='X'
    ),
    yaxis=dict(
        title='Y'
    ),
    zaxis=dict(
        title='Z'
    ),),
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=0
    )
)
fig = go.Figure(data=[trace1], layout=layout)
py.iplot(fig, filename='simple-3d-scatter')

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~taodav/0 or inside your plot.ly account where it is named 'simple-3d-scatter'

In [380]:
df["category"] = labels
df_listing_cat = df[['listing_url', 'category']]
df_listing_cat.loc[df_listing_cat["category"]==3]

                                listing_url  category
24     https://www.airbnb.com/rooms/6362362         3
25     https://www.airbnb.com/rooms/3544550         3
28     https://www.airbnb.com/rooms/8859380         3
50     https://www.airbnb.com/rooms/7772661         3
56     https://www.airbnb.com/rooms/8105221         3
60     https://www.airbnb.com/rooms/8095168         3
97     https://www.airbnb.com/rooms/4395578         3
109    https://www.airbnb.com/rooms/9015088         3
114    https://www.airbnb.com/rooms/4532538         3
116    https://www.airbnb.com/rooms/9387189         3
165    https://www.airbnb.com/rooms/1179538         3
171    https://www.airbnb.com/rooms/7731836         3
185    https://www.airbnb.com/rooms/8097708         3
189    https://www.airbnb.com/rooms/9587410         3
199    https://www.airbnb.com/rooms/3768745         3
203    https://www.airbnb.com/rooms/5487934         3
225    https://www.airbnb.com/rooms/9694921         3
238    https://www.airbnb.com/rooms/6569950         3
240    https://www.airbnb.com/rooms/9215782         3
252    https://www.airbnb.com/rooms/8755479         3
270    https://www.airbnb.com/rooms/7763878         3
271    https://www.airbnb.com/rooms/8088447         3
297    https://www.airbnb.com/rooms/1030411         3
308    https://www.airbnb.com/rooms/7922063         3
319    https://www.airbnb.com/rooms/3066740         3
382    https://www.airbnb.com/rooms/9508386         3
413    https://www.airbnb.com/rooms/7826541         3
424    https://www.airbnb.com/rooms/1715582         3
428    https://www.airbnb.com/rooms/7325455         3
433    https://www.airbnb.com/rooms/8653843         3
...                                     ...       ...
3450   https://www.airbnb.com/rooms/4485424         3
3477   https://www.airbnb.com/rooms/8583457         3
3482   https://www.airbnb.com/rooms/9508837         3
3505   https://www.airbnb.com/rooms/8136553         3
3508   https://www.airbnb.com/rooms/4557204         3
3513   https://www.airbnb.com/rooms/3817141         3
3552   https://www.airbnb.com/rooms/8507873         3
3562   https://www.airbnb.com/rooms/5040885         3
3575   https://www.airbnb.com/rooms/4454264         3
3580  https://www.airbnb.com/rooms/10248139         3
3585   https://www.airbnb.com/rooms/8613792         3
3588   https://www.airbnb.com/rooms/7025898         3
3604   https://www.airbnb.com/rooms/9368677         3
3605   https://www.airbnb.com/rooms/6837338         3
3623   https://www.airbnb.com/rooms/8670484         3
3624   https://www.airbnb.com/rooms/9727246         3
3632   https://www.airbnb.com/rooms/9863565         3
3636   https://www.airbnb.com/rooms/6586979         3
3644   https://www.airbnb.com/rooms/8051134         3
3658   https://www.airbnb.com/rooms/9217030         3
3721   https://www.airbnb.com/rooms/9533803         3
3738   https://www.airbnb.com/rooms/5728739         3
3747   https://www.airbnb.com/rooms/7857241         3
3749   https://www.airbnb.com/rooms/3963320         3
3765   https://www.airbnb.com/rooms/9262389         3
3770   https://www.airbnb.com/rooms/7853498         3
3797  https://www.airbnb.com/rooms/10118341         3
3806   https://www.airbnb.com/rooms/5458027         3
3811   https://www.airbnb.com/rooms/8578490         3
3814   https://www.airbnb.com/rooms/8902327         3

[328 rows x 2 columns]

In [381]:
category_mappings = {
    2: "modern",
    1: "luxury",
    4: "tourist",
    0: "homey",
    3: "quiet"
}

In [382]:
with open('agg.pickle', 'rb') as handle:
    agg1 = pickle.load(handle)

In [383]:
keys = {}
for field in ["neighbourhood", "property_type", "room_type", "bed_type"]:
    val_types = df[field].unique()
    val_map = dict.fromkeys(val_types)
    for i, el in enumerate(val_types):
        val_map[el] = i
    keys[field] = val_map
with open("keys.json", 'w') as f:
        json.dump(keys, f)

In [384]:
new = data
new["event_suitable"] = train_input["event_suitable"]
new[["id", "event_suitable"]]

            id event_suitable
0       241032          False
1       953595          False
2      3308979          False
3      7421966            NaN
4       278830          False
5      5956968          False
6      1909058          False
7       856550          False
8      4948745          False
9      2493658          False
10      175576          False
11     4454295          False
12     3883392          False
13     8889257          False
14     5680462           True
15     8988178          False
16     3245876          False
17     4933447          False
18     7735464            NaN
19     6291829          False
20     9218403          False
21     4125779          False
22     8942678          False
23    10106055            NaN
24     6362362          False
25     3544550          False
26     9025039            NaN
27     3200646          False
28     8859380          False
29     4520099          False
...        ...            ...
3788   7745196          False
3789   4645405          False
3790   2755730          False
3791   7949448          False
3792   9288840            NaN
3793   3312406          False
3794   6621924          False
3795   5673552           True
3796    609701          False
3797  10118341          False
3798   2614387          False
3799   7735100          False
3800   5482204            NaN
3801   4524575          False
3802   8562314            NaN
3803   9698202          False
3804   7178490          False
3805   8054902          False
3806   5458027          False
3807   4940491          False
3808   1844791          False
3809   6120046          False
3810    262764          False
3811   8578490          False
3812   3383329          False
3813   8101950          False
3814   8902327          False
3815  10267360            NaN
3816   9604740            NaN
3817  10208623            NaN

[3818 rows x 2 columns]

In [385]:
data["neighbourhood"].unique()

array(['Queen Anne', nan, 'Ballard', 'Phinney Ridge', 'Fremont',
       'Lower Queen Anne', 'Westlake', 'Wallingford', 'Green Lake',
       'Minor', 'Madrona', 'Harrison/Denny-Blaine', 'Leschi',
       'University District', 'Roosevelt', 'Madison Park', 'Capitol Hill',
       'Atlantic', 'North Beacon Hill', 'Central Business District',
       'Pike Place Market', 'Pike Market', 'Eastlake', 'Portage Bay',
       'South Lake Union', 'Magnolia', 'Belltown',
       'International District', 'Yesler Terrace', 'First Hill',
       'Pioneer Square', 'Gatewood', 'The Junction', 'Arbor Heights',
       'Alki', 'North Admiral', 'Crown Hill', 'Genesee', 'Fairmount Park',
       'Interbay', 'Industrial District', 'Holly Park',
       'South Beacon Hill', 'Greenwood', 'Bitter Lake', 'Fauntleroy',
       'Mount Baker', 'Columbia City', 'Seward Park', 'Brighton',
       'South Delridge', 'Highland Park', 'High Point', 'View Ridge',
       'Windermere', 'Dunlap', 'Rainier Beach', 'North Delridge',
       'Maple Leaf', 'Bryant', 'Ravenna', 'Wedgewood', 'Riverview',
       'Montlake', 'Stevens', 'Victory Heights', 'Mathews Beach',
       'Cedar Park', 'Meadowbrook', 'Olympic Hills',
       'North Beach/Blue Ridge', 'Broadview', 'Haller Lake', 'Pinehurst',
       'Licton Springs', 'North College Park', 'Laurelhurst', 'Seaview',
       'Georgetown', 'South Park', 'Roxhill'], dtype=object)